-- ═══════════════════════════════════════════════════════════════
-- NINA-AES — Référentiel géographique Mali (seed SQL)
-- ═══════════════════════════════════════════════════════════════
--
-- ⚠️  FICHIER GÉNÉRÉ — Ne pas éditer à la main.
--    Source de vérité : data/mali/regions.json + cercles.json
--    Régénération : node scripts/generate-seed-sql.mjs
--                 (ou : make seed-locations-generate)
--
-- Contenu :
--   - 20 régions (niveau 1)
--   - 142 cercles (niveau 2 ; total officiel attendu : 159)
--   - 10 communes (échantillon Bamako + chefs-lieux principaux)
--   - 0 arrondissements (niveau 3) — à ingérer ultérieurement via INSTAT
--   - 0 villages (niveau 6) — hors scope V1 (volume 12 712, source INSTAT requise)
--
-- Idempotent : INSERT ... ON CONFLICT (code) DO UPDATE.
-- Schéma isolé : `geo_ref` — n'interfère pas avec public.locations (Prisma).
-- ═══════════════════════════════════════════════════════════════

SET client_encoding = 'UTF8';
SET search_path = public;

-- ───────────────────────────────────────────────────────────────
-- Schema dédié au référentiel géographique statique
-- ───────────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS geo_ref;
COMMENT ON SCHEMA geo_ref IS 'Référentiel géographique Mali (régions, cercles, communes, arrondissements). Source de vérité : data/mali/*.json. Régénéré par scripts/generate-seed-sql.mjs.';

-- Table régions (niveau 1) — 19 régions + District de Bamako
CREATE TABLE IF NOT EXISTS geo_ref.regions (
  code            TEXT PRIMARY KEY,
  name_official   TEXT NOT NULL,
  name_short      TEXT NOT NULL,
  chef_lieu       TEXT NOT NULL,
  lat             NUMERIC(10, 7) NOT NULL,
  lng             NUMERIC(10, 7) NOT NULL,
  is_district     BOOLEAN NOT NULL DEFAULT FALSE,
  langues         TEXT[] NOT NULL DEFAULT '{}',
  statut_2023     TEXT,
  centroide_estime BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE geo_ref.regions IS '20 entités niveau 1 (19 régions + 1 District autonome de Bamako).';

-- Table cercles (niveau 2) — 159 attendus, 142 confirmés
CREATE TABLE IF NOT EXISTS geo_ref.cercles (
  code        TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  region_code TEXT NOT NULL REFERENCES geo_ref.regions(code) ON UPDATE CASCADE,
  lat         NUMERIC(10, 7) NOT NULL,
  lng         NUMERIC(10, 7) NOT NULL,
  confiance   TEXT NOT NULL DEFAULT 'haute' CHECK (confiance IN ('haute', 'moyenne', 'basse')),
  centroide_estime BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX IF NOT EXISTS cercles_region_idx ON geo_ref.cercles (region_code);

-- Table communes (niveau 4) — échantillon initial
CREATE TABLE IF NOT EXISTS geo_ref.communes (
  code        TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  parent_code TEXT NOT NULL,
  lat         NUMERIC(10, 7),
  lng         NUMERIC(10, 7)
);
CREATE INDEX IF NOT EXISTS communes_parent_idx ON geo_ref.communes (parent_code);

-- Table arrondissements (niveau 3) — réservée, vide pour V1
CREATE TABLE IF NOT EXISTS geo_ref.arrondissements (
  code        TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  cercle_code TEXT NOT NULL REFERENCES geo_ref.cercles(code) ON UPDATE CASCADE
);

-- ───────────────────────────────────────────────────────────────
-- Régions (niveau 1) — 20 entités
-- ───────────────────────────────────────────────────────────────
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-01', 'Région de Kayes', 'Kayes', 'Kayes', 14.446700, -11.444400, FALSE, ARRAY['FR', 'SNK', 'BM', 'FF']::TEXT[], 'Maintenue, périmètre réduit (cession de cercles vers Nioro et Kita)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-02', 'Région de Koulikoro', 'Koulikoro', 'Koulikoro', 12.862800, -7.559800, FALSE, ARRAY['FR', 'BM']::TEXT[], 'Maintenue, périmètre réduit (cession vers Dioïla et Nara)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-03', 'Région de Sikasso', 'Sikasso', 'Sikasso', 11.317600, -5.666500, FALSE, ARRAY['FR', 'BM', 'FF']::TEXT[], 'Maintenue, périmètre réduit (cession vers Bougouni et Koutiala)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-04', 'Région de Ségou', 'Ségou', 'Ségou', 13.431800, -6.215600, FALSE, ARRAY['FR', 'BM']::TEXT[], 'Maintenue, périmètre réduit (cession vers San)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-05', 'Région de Mopti', 'Mopti', 'Mopti', 14.484300, -4.182700, FALSE, ARRAY['FR', 'FF', 'BM', 'DJE']::TEXT[], 'Maintenue, périmètre fortement réduit (cession vers Bandiagara et Douentza)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-06', 'Région de Tombouctou', 'Tombouctou', 'Tombouctou', 16.772200, -3.008700, FALSE, ARRAY['FR', 'TMQ', 'DJE', 'FF']::TEXT[], 'Maintenue, périmètre réduit (cession vers Taoudénit)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-07', 'Région de Gao', 'Gao', 'Gao', 16.271100, -0.045900, FALSE, ARRAY['FR', 'DJE', 'TMQ']::TEXT[], 'Maintenue, périmètre réduit (cession vers Ménaka)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-08', 'Région de Kidal', 'Kidal', 'Kidal', 18.441200, 1.408000, FALSE, ARRAY['FR', 'TMQ']::TEXT[], 'Maintenue (couvre l''extrême Nord-Est)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-09', 'District de Bamako', 'Bamako', 'Bamako', 12.639200, -8.002900, TRUE, ARRAY['FR', 'BM']::TEXT[], 'Statut spécial — collectivité territoriale autonome (pas une région stricto sensu, mais traitée comme niveau 1 administratif)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-10', 'Région de Taoudénit', 'Taoudénit', 'Taoudénit', 22.678300, -3.979400, FALSE, ARRAY['FR', 'TMQ', 'HAU']::TEXT[], 'Confirmée — couvre l''extrême nord saharien (mines de sel historiques)', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-11', 'Région de Ménaka', 'Ménaka', 'Ménaka', 15.916000, 2.400000, FALSE, ARRAY['FR', 'TMQ', 'DJE']::TEXT[], 'Confirmée — couvre l''est saharien et le pourtour du fleuve Niger en aval de Gao', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-12', 'Région de Nioro', 'Nioro', 'Nioro du Sahel', 15.224700, -9.587800, FALSE, ARRAY['FR', 'SNK', 'BM']::TEXT[], 'Nouvelle région — détachée de Kayes', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-13', 'Région de Kita', 'Kita', 'Kita', 13.040700, -9.489500, FALSE, ARRAY['FR', 'BM', 'SNK']::TEXT[], 'Nouvelle région — détachée de Kayes', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-14', 'Région de Dioïla', 'Dioïla', 'Dioïla', 12.495300, -6.798400, FALSE, ARRAY['FR', 'BM']::TEXT[], 'Nouvelle région — détachée de Koulikoro', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-15', 'Région de Nara', 'Nara', 'Nara', 15.170100, -7.285300, FALSE, ARRAY['FR', 'BM', 'FF']::TEXT[], 'Nouvelle région — détachée de Koulikoro', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-16', 'Région de Bougouni', 'Bougouni', 'Bougouni', 11.416700, -7.483300, FALSE, ARRAY['FR', 'BM']::TEXT[], 'Nouvelle région — détachée de Sikasso', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-17', 'Région de Koutiala', 'Koutiala', 'Koutiala', 12.391700, -5.464200, FALSE, ARRAY['FR', 'BM']::TEXT[], 'Nouvelle région — détachée de Sikasso', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-18', 'Région de San', 'San', 'San', 13.303300, -4.896400, FALSE, ARRAY['FR', 'BM']::TEXT[], 'Nouvelle région — détachée de Ségou', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-19', 'Région de Bandiagara', 'Bandiagara', 'Bandiagara', 14.350000, -3.611100, FALSE, ARRAY['FR', 'FF']::TEXT[], 'Nouvelle région — détachée de Mopti, couvre le pays Dogon', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.regions (code, name_official, name_short, chef_lieu, lat, lng, is_district, langues, statut_2023, centroide_estime) VALUES ('ML-20', 'Région de Douentza', 'Douentza', 'Douentza', 15.002800, -2.946900, FALSE, ARRAY['FR', 'FF', 'DJE']::TEXT[], 'Nouvelle région — détachée de Mopti', FALSE) ON CONFLICT (code) DO UPDATE SET name_official = EXCLUDED.name_official, name_short = EXCLUDED.name_short, chef_lieu = EXCLUDED.chef_lieu, lat = EXCLUDED.lat, lng = EXCLUDED.lng, is_district = EXCLUDED.is_district, langues = EXCLUDED.langues, statut_2023 = EXCLUDED.statut_2023, centroide_estime = EXCLUDED.centroide_estime;

-- ───────────────────────────────────────────────────────────────
-- Cercles (niveau 2) — 142 confirmés / 159 attendus
-- ───────────────────────────────────────────────────────────────
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-01', 'Kayes', 'ML-01', 14.446700, -11.444400, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-02', 'Bafoulabé', 'ML-01', 13.807300, -10.831100, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-03', 'Diéma', 'ML-01', 14.541700, -9.183300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-04', 'Kéniéba', 'ML-01', 12.850000, -11.233300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-05', 'Yélimané', 'ML-01', 15.133300, -10.566700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-12-01', 'Nioro du Sahel', 'ML-12', 15.224700, -9.587800, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-13-01', 'Kita', 'ML-13', 13.040700, -9.489500, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-02-01', 'Koulikoro', 'ML-02', 12.862800, -7.559800, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-02-02', 'Banamba', 'ML-02', 13.550000, -7.450000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-02-03', 'Kangaba', 'ML-02', 11.933300, -8.416700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-02-04', 'Kati', 'ML-02', 12.744400, -8.073100, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-02-05', 'Kolokani', 'ML-02', 13.573300, -8.036700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-14-01', 'Dioïla', 'ML-14', 12.495300, -6.798400, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-14-02', 'Fana', 'ML-14', 12.766700, -6.950000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-15-01', 'Nara', 'ML-15', 15.170100, -7.285300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-01', 'Sikasso', 'ML-03', 11.317600, -5.666500, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-02', 'Kadiolo', 'ML-03', 10.550000, -5.750000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-03', 'Kolondiéba', 'ML-03', 11.086700, -6.898300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-01', 'Bougouni', 'ML-16', 11.416700, -7.483300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-02', 'Yanfolila', 'ML-16', 11.183300, -8.150000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-01', 'Koutiala', 'ML-17', 12.391700, -5.464200, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-02', 'Yorosso', 'ML-17', 12.350000, -4.783300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-01', 'Ségou', 'ML-04', 13.431800, -6.215600, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-02', 'Baraouéli', 'ML-04', 13.083300, -6.833300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-03', 'Bla', 'ML-04', 12.950000, -5.766700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-04', 'Macina', 'ML-04', 13.966700, -5.366700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-05', 'Niono', 'ML-04', 14.253300, -5.985800, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-01', 'San', 'ML-18', 13.303300, -4.896400, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-02', 'Tominian', 'ML-18', 13.300000, -4.583300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-01', 'Mopti', 'ML-05', 14.484300, -4.182700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-02', 'Djenné', 'ML-05', 13.905000, -4.555200, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-03', 'Ténenkou', 'ML-05', 14.433300, -4.916700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-04', 'Youwarou', 'ML-05', 15.450000, -4.083300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-01', 'Bandiagara', 'ML-19', 14.350000, -3.611100, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-02', 'Bankass', 'ML-19', 14.083300, -3.516700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-03', 'Koro', 'ML-19', 14.066700, -3.083300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-20-01', 'Douentza', 'ML-20', 15.002800, -2.946900, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-01', 'Tombouctou', 'ML-06', 16.772200, -3.008700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-02', 'Diré', 'ML-06', 16.270000, -3.383300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-03', 'Goundam', 'ML-06', 16.416700, -3.666700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-04', 'Gourma-Rharous', 'ML-06', 16.883300, -1.933300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-05', 'Niafunké', 'ML-06', 15.932200, -3.991100, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-10-01', 'Taoudénit', 'ML-10', 22.678300, -3.979400, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-10-02', 'Achouratt', 'ML-10', 18.750000, -3.550000, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-10-03', 'Boudjbéha', 'ML-10', 19.783300, -2.433300, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-10-04', 'Foum El Alba', 'ML-10', 21.350000, -4.050000, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-10-05', 'Al-Ourche', 'ML-10', 22.000000, -2.500000, 'basse', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-07-01', 'Gao', 'ML-07', 16.271100, -0.045900, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-07-02', 'Ansongo', 'ML-07', 15.666700, 0.500000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-07-03', 'Bourem', 'ML-07', 16.950000, -0.350000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-11-01', 'Ménaka', 'ML-11', 15.916000, 2.400000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-11-02', 'Inékar', 'ML-11', 15.933300, 2.016700, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-11-03', 'Andéramboukane', 'ML-11', 15.408300, 3.043600, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-11-04', 'Tidermène', 'ML-11', 17.116700, 1.850000, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-08-01', 'Kidal', 'ML-08', 18.441200, 1.408000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-08-02', 'Abeïbara', 'ML-08', 19.316700, 1.733300, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-08-03', 'Tessalit', 'ML-08', 20.200000, 1.016700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-08-04', 'Tin-Essako', 'ML-08', 18.683300, 2.450000, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-09-01', 'Commune I de Bamako', 'ML-09', 12.666700, -7.983300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-09-02', 'Commune II de Bamako', 'ML-09', 12.650000, -7.966700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-09-03', 'Commune III de Bamako', 'ML-09', 12.650000, -8.000000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-09-04', 'Commune IV de Bamako', 'ML-09', 12.633300, -8.050000, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-09-05', 'Commune V de Bamako', 'ML-09', 12.600000, -8.016700, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-09-06', 'Commune VI de Bamako', 'ML-09', 12.616700, -7.933300, 'haute', FALSE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-06', 'Ambidédi', 'ML-01', 14.992577, -11.793683, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-07', 'Aourou', 'ML-01', 14.964697, -11.586339, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-08', 'Diamou', 'ML-01', 14.086561, -11.262498, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-09', 'Oussoubidiagna', 'ML-01', 14.245077, -10.461587, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-10', 'Ségala', 'ML-01', 14.760813, -12.123862, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-01-11', 'Sadiola', 'ML-01', 13.891613, -11.705438, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-04', 'Dandérésso', 'ML-03', 11.486428, -5.482173, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-05', 'Kignan', 'ML-03', 11.851643, -6.012309, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-06', 'Kléla', 'ML-03', 11.687948, -5.663653, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-07', 'Lobougoula', 'ML-03', 11.042911, -5.981279, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-08', 'Loulouni', 'ML-03', 10.894766, -5.607981, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-03-09', 'Nièna', 'ML-03', 11.425668, -6.349073, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-06', 'Barouéli', 'ML-04', 13.072827, -6.831773, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-07', 'Dioro', 'ML-04', 13.689042, -5.831384, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-08', 'Farako', 'ML-04', 13.410104, -6.388549, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-09', 'Nampala', 'ML-04', 15.279241, -5.551756, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-10', 'Sokolo', 'ML-04', 14.741425, -6.120933, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-11', 'Markala', 'ML-04', 13.685860, -6.068613, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-04-12', 'Sarro', 'ML-04', 13.720861, -5.238604, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-05', 'Konna', 'ML-05', 14.944140, -3.890387, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-06', 'Korientzé', 'ML-05', 15.393401, -3.783040, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-05-07', 'Sofara', 'ML-05', 14.017120, -4.231219, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-06', 'Bintagoungou', 'ML-06', 16.737589, -3.731045, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-07', 'Saraféré', 'ML-06', 15.823207, -3.696052, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-08', 'Bambara Maoudé', 'ML-06', 15.851033, -2.786112, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-09', 'Léré', 'ML-06', 15.716098, -4.902164, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-10', 'Gossi', 'ML-06', 15.819721, -1.310105, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-11', 'Tonka', 'ML-06', 16.137041, -3.749054, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-12', 'Ber', 'ML-06', 16.839467, -2.526741, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-06-13', 'Gargando', 'ML-06', 16.467793, -4.168862, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-08-05', 'Aguel-Hoc', 'ML-08', 19.464192, 0.857362, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-11-05', 'Anouzagrène', 'ML-11', 15.537085, 2.497179, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-12-02', 'Diangounté', 'ML-12', 14.297576, -10.029834, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-12-03', 'Sandaré', 'ML-12', 14.703480, -10.305606, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-12-04', 'Troungoumbé', 'ML-12', 15.265397, -9.229957, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-12-05', 'Béma', 'ML-12', 15.043041, -9.353175, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-13-02', 'Sagabari', 'ML-13', 12.583731, -9.803129, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-13-03', 'Sébékoro', 'ML-13', 12.962708, -8.987956, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-13-04', 'Toukoto', 'ML-13', 13.447990, -9.876750, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-13-05', 'Séféto', 'ML-13', 14.139720, -9.827287, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-13-06', 'Sirakoro', 'ML-13', 12.682590, -9.228869, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-14-03', 'Banco', 'ML-14', 12.099169, -6.524494, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-14-04', 'Béléko', 'ML-14', 14.036695, -7.133372, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-14-05', 'Massigui', 'ML-14', 11.861314, -6.771489, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-14-06', 'Ména', 'ML-14', 11.471895, -7.611630, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-15-02', 'Ballé', 'ML-15', 15.339957, -8.583521, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-15-03', 'Dilly', 'ML-15', 14.999130, -7.668864, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-15-04', 'Mourdiah', 'ML-15', 14.471924, -7.471631, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-15-05', 'Guiré', 'ML-15', 14.641722, -6.691855, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-15-06', 'Fallou', 'ML-15', 14.599070, -7.932793, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-03', 'Garalo', 'ML-16', 10.992719, -7.436939, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-04', 'Koumantou', 'ML-16', 11.408609, -6.846414, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-05', 'Sélingué', 'ML-16', 11.642335, -8.193146, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-06', 'Ouélessébougou', 'ML-16', 11.991842, -7.909479, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-07', 'Kadiala', 'ML-16', 12.805454, -5.708573, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-08', 'Fakola', 'ML-16', 10.550731, -6.916953, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-16-09', 'Dogo', 'ML-16', 15.168402, -4.431335, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-03', 'M''Péssoba', 'ML-17', 12.665480, -5.720691, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-04', 'Molobala', 'ML-17', 12.176978, -5.331497, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-05', 'Koury', 'ML-17', 12.181178, -4.801671, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-06', 'Konséguéla', 'ML-17', 12.403713, -5.885751, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-07', 'Kouniana', 'ML-17', 12.571965, -5.126157, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-17-08', 'Zangasso', 'ML-17', 12.659614, -4.599985, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-03', 'Kimparana', 'ML-18', 12.834733, -4.924440, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-04', 'Yangasso', 'ML-18', 13.069595, -5.322084, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-05', 'Fangasso', 'ML-18', 13.527014, -4.446475, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-06', 'Mandiakuy', 'ML-18', 13.021079, -4.462934, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-18-07', 'Sy', 'ML-18', 13.600433, -4.978182, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-20-02', 'Boré', 'ML-20', 14.396576, -2.971095, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-20-03', 'Hombori', 'ML-20', 15.283116, -1.699074, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-20-04', 'N''Gouma', 'ML-20', 15.637890, -3.370612, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-20-05', 'Mondoro', 'ML-20', 14.675869, -1.950094, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-20-06', 'Boni', 'ML-20', 15.076876, -2.221140, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-04', 'Kendié', 'ML-19', 14.675756, -3.510421, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-05', 'Ningari', 'ML-19', 14.662020, -3.274121, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-06', 'Sangha', 'ML-19', 14.468356, -3.306466, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-07', 'Kani', 'ML-19', 12.135503, -6.777219, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;
INSERT INTO geo_ref.cercles (code, name, region_code, lat, lng, confiance, centroide_estime) VALUES ('ML-19-08', 'Sokoura', 'ML-19', 14.538061, -4.090354, 'moyenne', TRUE) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, region_code = EXCLUDED.region_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng, confiance = EXCLUDED.confiance, centroide_estime = EXCLUDED.centroide_estime;

-- ───────────────────────────────────────────────────────────────
-- Communes (échantillon 10 entrées)
-- ───────────────────────────────────────────────────────────────
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-09-C01', 'Commune I', 'ML-09', 12.675000, -7.965000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-09-C02', 'Commune II', 'ML-09', 12.650000, -7.990000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-09-C03', 'Commune III', 'ML-09', 12.650000, -8.010000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-09-C04', 'Commune IV', 'ML-09', 12.625000, -8.050000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-09-C05', 'Commune V', 'ML-09', 12.600000, -8.020000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-09-C06', 'Commune VI', 'ML-09', 12.575000, -7.940000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-02-C01', 'Kati', 'ML-02-04', 12.747500, -8.070000) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-05-C01', 'Mopti', 'ML-05-01', 14.484300, -4.182700) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-04-C01', 'Ségou', 'ML-04-01', 13.431800, -6.215600) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;
INSERT INTO geo_ref.communes (code, name, parent_code, lat, lng) VALUES ('ML-03-C01', 'Sikasso', 'ML-03-01', 11.317600, -5.666500) ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, parent_code = EXCLUDED.parent_code, lat = EXCLUDED.lat, lng = EXCLUDED.lng;

-- ───────────────────────────────────────────────────────────────
-- Message de fin
-- ───────────────────────────────────────────────────────────────
DO $$
DECLARE
  n_regions INTEGER;
  n_cercles INTEGER;
  n_communes INTEGER;
BEGIN
  SELECT COUNT(*) INTO n_regions  FROM geo_ref.regions;
  SELECT COUNT(*) INTO n_cercles  FROM geo_ref.cercles;
  SELECT COUNT(*) INTO n_communes FROM geo_ref.communes;
  RAISE NOTICE '============================================';
  RAISE NOTICE '✅ NINA-AES — Référentiel Mali seedé';
  RAISE NOTICE '   Régions   : % / 20 (19 régions + District)',  n_regions;
  RAISE NOTICE '   Cercles   : % / 159 attendus',                n_cercles;
  RAISE NOTICE '   Communes  : % (échantillon)',                 n_communes;
  RAISE NOTICE '   Arrondissements : 0 (à ingérer V2 via INSTAT)';
  RAISE NOTICE '   Villages         : 0 (hors scope V1, 12 712 attendus via INSTAT)';
  RAISE NOTICE '============================================';
END $$;
